In [1]:
import pandas as pd

In [ ]:
liverFunction = pd.read_csv(r"C:\Users\direk\OneDrive\Desktop\data_diseasePredictor\liver_function.csv")
liverFunction = liverFunction.drop("risk_label", axis=1)
liverFunction.head()

,alt,ast,alp,bilirubin_total,bilirubin_direct,albumin,total_protein
0,47.08,32.46,123.82,0.62,0.09,3.71,6.14
1,44.25,34.70,108.97,0.72,0.16,4.33,7.66
2,40.28,28.88,84.75,0.46,0.11,4.17,6.37
3,41.51,28.79,90.40,0.84,0.25,4.12,6.32
4,95.13,78.01,90.61,0.45,0.05,3.93,6.79

In [28]:
def liver_disease(row):
    score = 0

    if row["alt"] > 150 or row["ast"] > 150:
        return "Critical"

    if row["alt"] > 80 or row["ast"] > 80:
        score += 2
    elif row["alt"] > 40 or row["ast"] > 40:
        score += 1
    
    if row["bilirubin_total"] > 2:
        score += 1

    if row["albumin"] < 3:
        score += 1

    if score >= 3:
        return "High"
    elif score >= 1:
        return "Medium"
    else:
        return "Low"


def fatty_liver(row):
    if row["alt"] > 120:
        return "Critical"
    elif row["alt"] > row["ast"] and row["alt"] > 50:
        return "High"
    elif row["alt"] > row["ast"]:
        return "Medium"
    else:
        return "Low"


def hepatitis(row):
    if row["alt"] > 200 or row["ast"] > 200:
        return "Critical"
    elif row["alt"] > 100 or row["ast"] > 100:
        return "High"
    elif row["alt"] > 60 or row["ast"] > 60:
        return "Medium"
    else:
        return "Low"

In [29]:
liverFunction["liver_disease"] = liverFunction.apply(liver_disease, axis=1)
liverFunction["fatty_liver"] = liverFunction.apply(fatty_liver, axis=1)
liverFunction["hepatitis"] = liverFunction.apply(hepatitis, axis=1)
liverFunction.head()

,alt,ast,alp,bilirubin_total,bilirubin_direct,albumin,total_protein,liver_disease,fatty_liver,hepatitis
0,47.08,32.46,123.82,0.62,0.09,3.71,6.14,Medium,Medium,Low
1,44.25,34.70,108.97,0.72,0.16,4.33,7.66,Medium,Medium,Low
2,40.28,28.88,84.75,0.46,0.11,4.17,6.37,Medium,Medium,Low
3,41.51,28.79,90.40,0.84,0.25,4.12,6.32,Medium,Medium,Low
4,95.13,78.01,90.61,0.45,0.05,3.93,6.79,Medium,High,Medium

In [ ]:
LABEL_MAPPING = {
    "Low": "low",
    "Normal": "moderate",
    "Medium": "moderate",
    "High": "high",
    "Critical": "critical"
}

NUM_MAPPING = {
    "low": 0,
    "moderate": 1,
    "high": 2,
    "critical": 3
}

In [30]:
liverFunction["liver_disease"] = liverFunction["liver_disease"].map(LABEL_MAPPING)
liverFunction["fatty_liver"] = liverFunction["fatty_liver"].map(LABEL_MAPPING)
liverFunction["hepatitis"] = liverFunction["hepatitis"].map(LABEL_MAPPING)
liverFunction.head()

,alt,ast,alp,bilirubin_total,bilirubin_direct,albumin,total_protein,liver_disease,fatty_liver,hepatitis
0,47.08,32.46,123.82,0.62,0.09,3.71,6.14,moderate,moderate,low
1,44.25,34.70,108.97,0.72,0.16,4.33,7.66,moderate,moderate,low
2,40.28,28.88,84.75,0.46,0.11,4.17,6.37,moderate,moderate,low
3,41.51,28.79,90.40,0.84,0.25,4.12,6.32,moderate,moderate,low
4,95.13,78.01,90.61,0.45,0.05,3.93,6.79,moderate,high,moderate

In [31]:
liverFunction["liver_disease_num"] = liverFunction["liver_disease"].map(NUM_MAPPING)
liverFunction["fatty_liver_num"] = liverFunction["fatty_liver"].map(NUM_MAPPING)
liverFunction["hepatitis_num"] = liverFunction["hepatitis"].map(NUM_MAPPING)
liverFunction.head()

,alt,ast,alp,bilirubin_total,bilirubin_direct,albumin,total_protein,liver_disease,fatty_liver,hepatitis,liver_disease_num,fatty_liver_num,hepatitis_num
0,47.08,32.46,123.82,0.62,0.09,3.71,6.14,moderate,moderate,low,1,1,0
1,44.25,34.70,108.97,0.72,0.16,4.33,7.66,moderate,moderate,low,1,1,0
2,40.28,28.88,84.75,0.46,0.11,4.17,6.37,moderate,moderate,low,1,1,0
3,41.51,28.79,90.40,0.84,0.25,4.12,6.32,moderate,moderate,low,1,1,0
4,95.13,78.01,90.61,0.45,0.05,3.93,6.79,moderate,high,moderate,1,2,1

In [32]:
df = pd.concat([
    bloodReport,
    lipidProfile,
    vitamin_dReport,
    hormoneReport,
    kidneyFunction,
    liverFunction
], axis=1)

In [33]:
df.head()

,wbc,rbc,hemoglobin,hematocrit,platelets,glucose,creatinine,bun,diabetes_risk,anemia_risk,...,bilirubin_total,bilirubin_direct,albumin,total_protein,liver_disease,fatty_liver,hepatitis,liver_disease_num,fatty_liver_num,hepatitis_num
0,8.25,5.17,16.60,50.58,241.24,90.71,0.52,8.73,low,low,...,0.62,0.09,3.71,6.14,moderate,moderate,low,1,1,0
1,12.31,5.56,15.89,47.11,267.77,94.68,0.73,5.40,low,low,...,0.72,0.16,4.33,7.66,moderate,moderate,low,1,1,0
2,14.05,4.24,14.59,42.95,235.38,81.69,0.82,8.31,low,low,...,0.46,0.11,4.17,6.37,moderate,moderate,low,1,1,0
3,9.78,5.03,13.53,40.59,259.60,78.88,1.28,12.93,low,low,...,0.84,0.25,4.12,6.32,moderate,moderate,low,1,1,0
4,7.15,4.54,15.55,46.47,180.32,74.15,1.01,8.61,low,low,...,0.45,0.05,3.93,6.79,moderate,high,moderate,1,2,1

In [34]:
df["cardiovascular_risk"] = df[["heart_risk_num", "stroke_risk_num"]].mean(axis=1)
df["diabetes_risk_score"] = df["diabetes_risk_num"]
df["hypertension_risk"] = df["stroke_risk_num"]  # proxy
df["liver_risk"] = df[["liver_disease_num", "fatty_liver_num"]].mean(axis=1)
df["kidney_risk"] = df[["kidney_disease_num", "renal_failure_num"]].mean(axis=1)
df.head()

,wbc,rbc,hemoglobin,hematocrit,platelets,glucose,creatinine,bun,diabetes_risk,anemia_risk,...,fatty_liver,hepatitis,liver_disease_num,fatty_liver_num,hepatitis_num,cardiovascular_risk,diabetes_risk_score,hypertension_risk,liver_risk,kidney_risk
0,8.25,5.17,16.60,50.58,241.24,90.71,0.52,8.73,low,low,...,moderate,low,1,1,0,0.5,0,0,1.0,0.0
1,12.31,5.56,15.89,47.11,267.77,94.68,0.73,5.40,low,low,...,moderate,low,1,1,0,0.0,0,0,1.0,0.5
2,14.05,4.24,14.59,42.95,235.38,81.69,0.82,8.31,low,low,...,moderate,low,1,1,0,2.0,0,2,1.0,1.5
3,9.78,5.03,13.53,40.59,259.60,78.88,1.28,12.93,low,low,...,moderate,low,1,1,0,0.5,0,0,1.0,0.0
4,7.15,4.54,15.55,46.47,180.32,74.15,1.01,8.61,low,low,...,high,moderate,1,2,1,1.5,0,2,1.5,1.5